BoxLayout:
    id: mainBox

    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            BoxLayout:
                orientation: 'vertical'
                Button:
                    id: BUTTON_FUNCTION_HERE
                    text: 'List Items'
                    on_press: app.button_creator()

                Button:
                    id: BUTTON_FUNCTION_HERE
                    text: 'Hire Items'
                    on_press: app.list_in_stock()

                Button:
                    id: BUTTON_FUNCTION_HERE
                    text: 'Return Items'
                    on_press: app.list_out_stock()

                Button:
                    id: BUTTON_FUNCTION_HERE
                    text: 'Confirm'
                    on_press: app.button_creator()

                Button:
                    id: addButton
                    text: 'Add New Entry'
                    on_release: app.press_add()

                Button:
                    id: BUTTON_FUNCTION_HERE
                    text: 'Save and Exit'
                    on_press: app.exit_program()

            GridLayout:
                id: entriesBox
                cols: 3
                orientation: 'vertical'



        Label:
            id: BUTTON_FUNCTION_HERE
            font_size: 20
            text: app.status_text
            color: (1, 1, 0, 1)
